<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('foods', function (Blueprint $table) {
            // Add the FULLTEXT index to both 'name' and 'description' columns
            $table->fullText(['name', 'description']);
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('foods', function (Blueprint $table) {
            // Drop the FULLTEXT index if the migration is rolled back
            $table->dropIndex(['name', 'description']); // The index name is automatically generated by Laravel/Doctrine DBAL
        });
    }
};
